### PR TITLE
fix: update styling for EntityDataReminder

### LINKED ISSUE #50: slight rendering errors when there are no matching repos
noticed two small things on the default dark theme

1. helper text is unreadable with highlight
2. can we move "► Why am I seeing all workspaces?" to below the <hr /> instead of overlapping it?

https://github.com/coder/backstage-plugins/assets/22407953/02f70991-9895-436d-8bf3-7320e461f041

### PR DESCRIPTION
**Pull request by Parkreiner**
Closes #50 

## Changes made
- Split `DataEntityReminder` off into a separate component
   - Updated the semantics and improved screen reader support
   - Updated styling to work consistently across light mode and dark mode
   - Changed some alignment on the text elements
   - Increased the width of the reminder button to make it easier to click, and added hover styling
- Updated logic for the `useId` polyfill
   - Since we have React 18 now, the file will return out the native `useId` when available, but fall back to the polyfill when on React 16/17

Screenshot 2024-03-18 at 11 57 08 AM
Screenshot 2024-03-18 at 11 57 19 AM

### CODE REVIEW

File: plugins/backstage-plugin-coder/src/hooks/hookPolyfills.ts [hunk 1]
```diff
@@ -13,14 +13,17 @@ let idCounter = 0;
...
-    return String(idCounter);
+    return `:r${idCounter}:`;
   });
 
-  return `:r${readonlyIdRoot}:`;
+  return readonlyId;
 }
+
+export const useId =
+  typeof React.useId === 'undefined' ? useIdPolyfill : React.useId;
```
Comment (Parkreiner) [inline plugins/backstage-plugin-coder/src/hooks/hookPolyfills.ts:29]: I think I could also change the condition to `React.useId === undefined`, but this approach is technically safer, since it can't throw

**Review by Kira-Pilot — APPROVED** [review]
Thanks for cleaning this up! Looks good to me!
